"""empty message

Revision ID: 8636ae1f40a0
Revises: c5f6e683f913
Create Date: 2019-12-10 20:34:46.741167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8636ae1f40a0'
down_revision = 'c5f6e683f913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('number_people', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'number_people')
    # ### end Alembic commands ###
